### ISSUE TITLE
This is not bug but a feature request

### ISSUE THREAD

**Issue by dineshbhagat** [smoketurner/dropwizard-swagger#103]
I am using Swagger-api: 2.0.0
The reason I am using this version is that it has a feature to mark APIs as a deprecated.
[online swagger editor](http://editor.swagger.io/?_ga=2.6759223.440671946.1523941097-1757111219.1523941097#/)
If it is possilbe with version com.smoketurner:dropwizard-swagger: 1.2.4-2, please let me know.

Thanks,

**Comment by jplock** [comment]
I need to upgrade this library to 2.0, just haven’t had time yet.

**Comment by bhagatdinesh** [comment]
cool, let's skip 2.0 since 3.0 is [here](https://github.com/OAI/OpenAPI-Specification)
