### ISSUE TITLE
Authorization Header not getting sent anymore since 1.2.2-1

### ISSUE THREAD

**Issue by TobiasGoerke** [smoketurner/dropwizard-swagger#105]
After upgrading dropwizard to 1.3.1 and dropwizard-swagger to 1.3.0-1 I noticed the authorization header does not get sent anymore.
The last version of dropwizard-swagger that is still sending the authorization header after authorizing is 1.1.2-1.

**Comment by maksymgendin** [comment]
You have to mark your secured endpoints with `@ApiOperation`, for example:
```java
@ApiOperation(value = "", authorizations = {@Authorization(value = "password-scheme")})
```
and define somewhere your authorization scheme, for example:
```java
@SwaggerDefinition(
        securityDefinition = @SecurityDefinition(
                oAuth2Definitions = @OAuth2Definition(
                        tokenUrl = "/token",
                        flow = io.swagger.annotations.OAuth2Definition.Flow.PASSWORD,
                        key = "password-scheme"
                )
        )
)
```

**Comment by TobiasGoerke** [comment]
Thanks for your quick response.
Adding the Authorization annotation to ApiOperation annotation did the trick.
Thanks again!
