### ISSUE TITLE
Google guava version

### ISSUE THREAD

**Issue by jammasterj89** [smoketurner/dropwizard-swagger#111]
Hi, 

[Snyk](https://snyk.io) reports that the version of com.google.guava:guava in use is vulnerable to Mad Gadget. They [recommend ](https://app.snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236)to upgrade to version 24.1.1 or higher. Can I ask if this upgrade is planned please?

Thank you!

**Comment by jplock** [comment]
The guava version is coming from dropwizard itself.  We'll need to wait until Dropwizard 2.0.0 is completed.

**Comment by jammasterj89** [comment]
@jplock thank you for clarifying.
