### ISSUE TITLE
Multiple "resourcePackage" configuration

### ISSUE THREAD

**Issue by DreamInSun** [smoketurner/dropwizard-swagger#112]
If I got more than one "resourcePackage" required to scan.

How can I setup in SwaggerBundleConfiguration.

` bootstrap.addBundle(new SwaggerBundle<TConfig>() {
            @Override
            protected SwaggerBundleConfiguration getSwaggerBundleConfiguration(TConfig config) {
                String scanRootPackage = config.getProjectConfig().getRootPackage() + ".resources";
                g_Logger.info("Auto Fill Swagger Scan Root Package is :" + scanRootPackage);
                config.getSwaggerBundleConfiguration().setResourcePackage(scanRootPackage);
                return  config.getSwaggerBundleConfiguration();
            }
        });`

**Comment by maksymgendin** [comment]
You can put multiple package names separated by a comma to "resourcePackage"

**Comment by DreamInSun** [comment]
> You can put multiple package names separated by a comma to "resourcePackage"
Thanks, I made it like that:
` /* Add Scan Root */
                List<String> scanPackageList = Lists.newArrayList();
                scanPackageList.add(config.getProjectConfig().getRootPackage() + ".resources");
                scanPackageList.add(BaseApplication.NAZGUL_CORE_ROOT + ".resources");
                /* */
                String scanRootPackage = Joiner.on(",").join(scanPackageList);
                g_Logger.info("Auto Fill Swagger Scan Root Package is :" + scanRootPackage);

                swaggerConfig.setResourcePackage(scanRootPackage);`
