### ISSUE TITLE
constant ClassNotFound exceptions

### ISSUE THREAD

**Issue by jnovotny** [smoketurner/dropwizard-swagger#115]
Hi,
I upgraded to swgagger 1.3.1-1 and my pom.xml has

`<dependency>

            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>1.3.1-1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.reflections</groupId>
                    <artifactId>reflections</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
`

however i get tons of 

Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.spi.ExtendedLoggerWrapper
...
org.reflections.ReflectionsException: could not get type for name javax.servlet.jsp.tagext.BodyTag
...
etc

This happens when launching the fat jar that is created.
What can I do?

**Comment by bdbull** [comment]
Adding an explicit dependency to 0.9.10 of reflections worked for me.
```
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.10</version>
</dependency>
```

**Comment by roryodonnell** [comment]
If downgrading the dependency is not an option, this also works.

```
logging:
  level: INFO
  loggers:
      "org.reflections": ERROR
```
