### ISSUE TITLE
/swagger-static is wrong if a basePath is defined in the app

### ISSUE THREAD

**Issue by reubenfirmin** [smoketurner/dropwizard-swagger#119]
If the contextPath is programmatically set in the Application, e.g. 

```
(environment.applicationContext as ContextHandler).contextPath = "/" + basePath()
```

then the swagger-static setup ends up being wrong:

```
    new AssetsBundle(
            "/swagger-static", configurationHelper.getSwaggerUriPath(), null, "swagger-assets")
        .run(environment);
```

Please make sure the contextPath is included in this.

**Comment by reubenfirmin** [comment]
The issue seems to be that the AssetsServlet that's created gets inserted at whatever the basepath is set to + /swagger-static.

Setting uriPrefix doesn't fix this.

**Comment by havenith** [comment]
This is still an issue
