### ISSUE TITLE
Not able to customise 'Example value' of the request body

### ISSUE THREAD

**Issue by JohnChangUK** [smoketurner/dropwizard-swagger#127]
There currently is no support for creating custom example values which the user can test the API with. The reason for this is to abstract the required fields as the user may not know what values to provide, 

Currently when loading the Swagger UI, the default 'Example Value' is shown below:

```
{
  "date": "2019-04-11",
  "type": "string",
  "value": "string",
  "shops": [
    "string"
  ]
}
```

What would be ideal is for the default 'Example Value' to be provided beforehand:
```
{
  "date": "2017-12-01",
  "type": "accessory",
  "value": "headphones",
  "shops": [ "traderjoe"]
}
```
This way the user is able to start testing the API with no further knowledge.

One way I got around this was to mark the fields `@ApiModelProperty` whilst providing an example value, (which only takes a string) 
`@ApiModelProperty(example = "[\"traderjoe\"]")`

However, there is no support for providing the example values as Arrays/Lists, as it get's interpreted as a string as shown below. There is currently no solution to this as far as I could tell. I have tried all the possible solutions, however they have all yet to work. This seems to have been resolved with SpringFox.
Related posts:
https://github.com/swagger-api/swagger-ui/issues/3465
https://stackoverflow.com/questions/40989038/swagger-apimodelproperty-example-value-for-liststring-property

```
{
  "date": "2017-12-01",
  "type": "accessory",
  "value": "headphones",
  "shops": "[\"traderjoe\"]"
}
```
Related issue: https://github.com/springfox/springfox/issues/2352

Furthermore, I have also tried providing an example as shown below:
```public Response output(@ApiParam(defaultValue = "thisWorks") @PathParam("metric") String metric, @ApiParam(examples = @Example(@ExampleProperty(value = "{\"inputs\": {\"entityType\": \"type\",\"token\": \"flower\"}"))) OrigRequest origRequest) {}```

The example value given above does not get shown and a lot of people have been encountering this issue. This issue still persists as shown in this related post: https://github.com/swagger-api/swagger-core/issues/1940

It would be great to see support for example values!

**Comment by revjtanton** [comment]
I think this would need to support 2.x version of Swagger for List/Array support.

**Comment by HebaIbrahemX** [comment]
Guys, any updates about this issue? Did anyone succeeded in manipulating example values?

**Comment by unckleg** [comment]
?

**Comment by parichayawalia** [comment]
encountered the same issue. would be great to add a support for this
