### ISSUE TITLE
Update to swagger-ui 2.1.4

### ISSUE THREAD

**Issue by danielfosse** [smoketurner/dropwizard-swagger#13]
You are using swagger-ui 2.1.2 in dropwizard-swagger 0.9.1 but the latest swagger-ui is 2.1.4 that contains lots of bugfixes. We have experienced one of those bugs and therefore would like to have the latest swagger-ui in dropwizard-swagger.

**Comment by jplock** [comment]
Fixed in https://github.com/smoketurner/dropwizard-swagger/commit/b92258ee8ef358cc208f1b905c688d11a7fe5281

**Comment by danielfosse** [comment]
thanks!
