### ISSUE TITLE
Releases since dropwizard 1.3.9.

### ISSUE THREAD

**Issue by nicholas-s-perkins** [smoketurner/dropwizard-swagger#135]
Hello,
I see that there have been several updates to  the master branch, but no releases since dropwizard 1.3.9, which was several dropwizard releases ago.
Is the next release of this on hold for any reason?

**Comment by jplock** [comment]
Nope, just haven’t had time yet. I’ll release one this week.

**Comment by jplock** [comment]
Just published v1.3.12-1 to maven central
