### ISSUE TITLE
Support of ﻿﻿﻿JsonTypeInfo

### ISSUE THREAD

**Issue by laurent-thiebaud-gisaia** [smoketurner/dropwizard-swagger#144]
Swagger now supports JsonTypeInfo and JsonSubTypes annotations, it would be great if  dropwizard-swagger did so (https://github.com/swagger-api/swagger-core/issues/280)

**Comment by dazraf** [comment]
any progress with this?

**Comment by jplock** [comment]
Anyone mind submitting a PR? Happy to review it.

**Comment by dazraf** [comment]
Apologies. Looks like the original issue in swagger-core still exists. Following up with their team. Can delete my comment above.

**Comment by FelixHoffmannLeanIX** [comment]
To the best of my knowledge this is still an issue.
