### ISSUE TITLE
Update readme version matix to include dropwizard 2.x

### ISSUE THREAD

**Issue by chris-orchard** [smoketurner/dropwizard-swagger#166]
Now that dropwizard 2.0.0 is available can you please update the version matrix to include this?
https://github.com/smoketurner/dropwizard-swagger#version-matrix

Also you have a `v2.0.0-1` release that isn't featured in the matrix.

Is this the version to use with dropwizard 2.0 or will `1.3.x` still work?

**Comment by chris-orchard** [comment]
So I've confirmed that `1.3.12-1` doesn't work with dropwizard 2.0, at least in my setup.

I get the following error due to the dependency `com.smoketurner:dropwizard-swagger:1.3.12-1 > io.dropwizard:dropwizard-auth:1.3.12`.
```
ERROR [2020-01-28 10:23:57,006] org.glassfish.grizzly.servlet.ServletHandler: service exception:
! java.lang.ClassNotFoundException: org.glassfish.jersey.server.internal.inject.AbstractValueFactoryProvider
```

I'm using [io.dropwizard.auth.AuthValueFactoryProvider](https://github.com/dropwizard/dropwizard/blob/release/2.0.x/dropwizard-auth/src/main/java/io/dropwizard/auth/AuthValueFactoryProvider.java) and need the dropwizard 2 version which has been updated to extend `AbstractValueParamProvider` instead of `AbstractValueFactoryProvider` it extends in 1.3.x.

**Comment by chrisrohr** [comment]
To add to this thread, I had to do the following as well to get validations to work with DW 2.x:

```
     <exclusions>
        <exclusion>
          <groupId>javax.validation</groupId>
          <artifactId>validation-api</artifactId>
        </exclusion>
      </exclusions>
```

Not exactly sure (yet) which dependency is bringing in the older validation-api but DW now brings in the jakarta one.  The symptom is that the older one doesn't define a couple of the new interface methods on `javax.validation.BootstrapConfiguration`.

**Comment by jplock** [comment]
Fixed readme in https://github.com/smoketurner/dropwizard-swagger/commit/d7ef59c808d437f48e917ef3721193b021e6c3ed
