### ISSUE TITLE
Is this bundle still supported?

### ISSUE THREAD

**Issue by chrisrohr** [smoketurner/dropwizard-swagger#197]
Hi,

Thank you for taking on this bundle and keeping it going.  I was curious based on the comments in #170 if this library was still supported.  If not is there any alternatives or is there any desire for assistance.  I would love to help if wanted, otherwise I can fork it and try to update it.

**Comment by jplock** [comment]
I’m happy to keep maintaining it but I no longer use it. Happy to review PRs and I’ll publish updates.

**Comment by chrisrohr** [comment]
Ok thank you. I can help with updates.
