### ISSUE TITLE
fmt-maven-plugin no longer supports Java 8

### ISSUE THREAD

**Issue by chrisrohr** [smoketurner/dropwizard-swagger#199]
Looks like in smoketurner/dropwizard-pom@4edf18b dependabot upgraded fmt-maven-plugin from 2.9 to 2.10.  If you look at https://github.com/coveooss/fmt-maven-plugin/issues/63 it seems like google stopped supporting Java 8 in the release that 2.10 is using.  I think this is why the Java 8 builds are failing here.  So I guess the options are:

1. Stop supporting Java 8 on this plugin (probably less desirable)
2. Downgrade the plugin to 2.9.1 in dropwizard-pom

Sorry I would have added this to that repo but I didn't see an issues tab.

**Comment by jplock** [comment]
Hmm that’s not fun

**Comment by chrisrohr** [comment]
Haha, agreed

**Comment by sandeepnkulkarni** [comment]
Removing support for Java 8 does not makes sense. Dropwizard 3 and 4 are not out yet and Dropwizard 2.1.x is the current released and it supports 8 still.

**Comment by jarl-dk** [comment]
I think this can be closed as support for java 8 has been removed.
