### ISSUE TITLE
Error "Could not render this component, see the console." when clicking the "Try it out" button

### ISSUE THREAD

**Issue by mahe1970** [smoketurner/dropwizard-swagger#206]
Hi,
when I press the "Try it out" button I get the error "Could not render this component, see console".
I use dropwizard-swagger in version 2.0.12-1.

This is the chrome console output:

> TypeError: Cannot read property 'apply' of null
>     at Object.e.requestInterceptor (actions.js:420)
>     at index.js:578
>     at c (runtime.js:45)
>     at Generator._invoke (runtime.js:271)
>     at Generator.e.<computed> [as next] (runtime.js:97)
>     at o (asyncToGenerator.js:5)
>     at s (asyncToGenerator.js:27)
>     at asyncToGenerator.js:34
>     at new Promise (<anonymous>)
>     at new t (_export.js:36)
> 
> TypeError: Cannot read property 'get' of null
>     at t.value (live-response.jsx:56)
>     at t.M.t.render (root-injects.jsx:93)
>     at u._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
>     at u._renderValidatedComponent (ReactCompositeComponent.js:819)
>     at u._updateRenderedComponent (ReactCompositeComponent.js:743)
>     at u._performComponentUpdate (ReactCompositeComponent.js:721)
>     at updateComponent (ReactCompositeComponent.js:642)
>     at u.receiveComponent (ReactCompositeComponent.js:544)
>     at Object.receiveComponent (ReactReconciler.js:122)
>     at Object.updateChildren (ReactChildReconciler.js:107)
> 

live-response.jsx line 56:
> const url = curlRequest.get("url")

The file live-response.jsx comes from the swagger-ui package (src/core/components)

Does anyone have an idea what I am doing wrong?

Best Regards
mahe1970

**Comment by KatseNarniaan** [comment]
I think this is probably the same as issue #210

**Comment by marcelstoer** [comment]
Should be closed as it's a dup of #210 (the other way round actually).

**Comment by asantosca** [comment]
Having the same problem. Tried getting the latest from master but still getting the same error.

**Comment by petusch** [comment]
So this isn't #210 issue. I've updated swagger and still got this issue. FYI: /swagger-static/index.html requests works fine

**Comment by asantosca** [comment]
We were able to solve this issue by getting the version `2.0.12.2` and removing the lines
```
        <#if customJavascriptPath??>
        requestInterceptor: (typeof customRequestInterceptor == 'function' ? customRequestInterceptor : null)
        </#if>
```

from src/main/resources/io/federecio/dropwizard/swagger/index.ftl

Although this fixed our issues, it is not a general solution, as it removes the interceptor for custom javascript.

**Comment by jnovotny** [comment]
This is STILL an issue making all of swagger pretty unusable. Is there a fork of the code somewhere that fixed this problem a year later?

**Comment by jnovotny** [comment]
Having the same problem 4/24/2021. Any new updates?

**Comment by jplock** [comment]
I’d be happy to review a PR if someone can submit one.

**Comment by jnovotny** [comment]
Ok thanks I'l see what I can do

**Comment by jnovotny** [comment]
Hi,

Just following up, it appears only a new release needs to be published to
maven central repository as the issue is fixed in code but maven has an
older version available.

Thanks, Jason

**Comment by dmitrypol** [comment]
any updates on this?

**Comment by jplock** [comment]
Not yet. I got a new machine and haven’t set up the ability to publish to maven central yet

**Comment by dmitrypol** [comment]
Just want to say I understand and appreciate your maintenance of this library

**Comment by roryodonnell** [comment]
AN update to this would please our PEN testing team !!!

**Comment by raviharshil27** [comment]
Any update on this ? This would also be important for us to use the new tag

**Comment by alainbodiguel** [comment]
Hi, same need here for an updated version in maven central. Too bad we can't help without the credentials!

**Comment by amcghie** [comment]
For anyone having the experiencing this issue.  I found the following workaround:
1. Create an "empty" custom request interceptor e.g. `swagger-static/custom-request-interceptor.js` in your `resources` directory
   ```javascript
   function customRequestInterceptor(request) {
       return request;
   }
   ```
2. Add a reference to this file in the `customJavascript` field of the `SwaggerBundleConfiguration` class e.g.:
    ```yaml
    swagger:
        customJavascript: "/swagger-static/custom-request-interceptor.js"
    ```
    or
    ```java
    bootstrap.addBundle(new SwaggerBundle<>() {
        protected SwaggerBundleConfiguration getSwaggerBundleConfiguration(ServiceConfiguration configuration) {
            SwaggerBundleConfiguration config = new SwaggerBundleConfiguration();
            config.setCustomJavascript("/swagger-static/custom-request-interceptor.js");

            return config;
        }
    });
    ```

**Comment by ankuagarwal** [comment]
When is the new released planned ?

**Comment by flybonzai** [comment]
Any movement on this?  I have tried some of the work-arounds above, but none of them seem to work for me.

**Comment by dmitrypol** [comment]
Any updates on this?
