### ISSUE TITLE
"Try it out" buttons throw errors in 2.0.12-1

### ISSUE THREAD

**Issue by KatseNarniaan** [smoketurner/dropwizard-swagger#210]
Try it out -> Execute buttons give only this kind of message: "😱 Could not render this component, see the console."

TypeError: p is null
    requestInterceptor actions.js:420
    e index.js:578
    Babel 6
    t _export.js:36
    exports Babel
    V index.js:498
    makeHttp index.js:780
    execute index.js:3763
    De actions.js:433
    $/</</< utils.js:137
    P Redux
    c wrap-actions.js:33
    r system.js:174
    z system.js:461
    Le actions.js:458
    $/</</< utils.js:137
    P Redux
    y spec-wrap-actions.js:9
    r system.js:174
    z system.js:461
    t execute.jsx:24
    React 14
    listen EventListener.js:29
    React 74
    P root-injects.jsx:69
    h index.js:161
    Hn index.js:180
    onload swagger:41
    EventHandlerNonNull* swagger:38

TypeError: c is null
    value live-response.jsx:56
    render root-injects.jsx:93
    React 9

When I take the swagger.json and paste it to https://editor.swagger.io/ I do not get such errors. I also tried another validator, and no errors found in the swagger.json.

**Comment by KatseNarniaan** [comment]
Also I would love to get some troubleshooting ideas, if anyone has any.

**Comment by KatseNarniaan** [comment]
Also is there anyone who has this working?

**Comment by KatseNarniaan** [comment]
Also I tried running the latest dropwizard-swagger's SampleApplication, and I get the same error there, too.

**Comment by KatseNarniaan** [comment]
This has something to do with this:
https://github.com/smoketurner/dropwizard-swagger/pull/182/files/3c2aceeb72375fa986185baa34c4bb44b097ed11#

When I remove the line:
`requestInterceptor: (typeof customRequestInterceptor == 'function' ? customRequestInterceptor : null)`
from src/main/resources/io/federecio/dropwizard/swagger/index.ftl
the buttons in "try it now" work again.

**Comment by laktech** [comment]
This PR fixed the problem for me. When can we expect a release?

**Comment by KatseNarniaan** [comment]
@jplock Is there a schedule for release? I kind of do not want to use local snapshots in production

**Comment by DrMattFaulkner** [comment]
> This PR fixed the problem for me. When can we expect a release?

Same here. This fixes it for me too. @jplock Any eta on the release?

**Comment by roryodonnell** [comment]
I've got this issue also `2.0.0-1` is clean, `2.0.12-1` causes issue 

😱 Could not render this component, see the console.

**Comment by marcelstoer** [comment]
Oh, glad I found this. Also looking forward to a new release.

**Comment by asantosca** [comment]
I'm having the same problem. Was it already released?

**Comment by roryodonnell** [comment]
When is the release due ?

**Comment by XN137** [comment]
we would also be interested in seeing a new release that includes this fix, thanks

**Comment by SaiWebApps** [comment]
Hi, when is the new release (with the fix for this issue) planned?
