### ISSUE TITLE
0.6.x version is not available in the center repository

### ISSUE THREAD

**Issue by bidiu** [smoketurner/dropwizard-swagger#23]
It seems that 0.6.x version is not available in the maven center repository, can this be fixed? Because I'm using dropwizard 0.8.0, and the newer version of dropwizard-swagger probably has some package conflict with it, as happens to me.

**Comment by dfc-production** [comment]
If you are in urgent need of that version, you could use version 0.6.x of https://github.com/federecio/dropwizard-swagger in the meantime, which this repository is forked from and is available at Maven central.

**Comment by benbek** [comment]
If you are in urgent need of that version, you could use version 0.6.x of https://github.com/federecio/dropwizard-swagger in the meantime, which this repository is forked from and is available at Maven central.

**Comment by bidiu** [comment]
That fixes my problem, thanks
