### ISSUE TITLE
Swagger not showing response

### ISSUE THREAD

**Issue by kuldeepiitg** [smoketurner/dropwizard-swagger#252]
Swagger not able to present response, which works fine in browser as a GET.

Showing "Could not render this component, see the console."

<img width="1440" alt="Screenshot 2022-01-16 at 2 02 20 PM" src="https://user-images.githubusercontent.com/1637382/149652944-50a2ecda-1199-4167-a87c-460c545d11e1.png">

**Comment by kuldeepiitg** [comment]
It is happening because of swagger version, it was not happening in 

`        <dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>2.0.0-1</version>
        </dependency>
`

But 2.0.0-1 had warnings on server start

**Comment by afboteroz** [comment]
It happens the same to me, i tested master and don't happen anymore, when are you planning to do a release?

**Comment by kuldeepiitg** [comment]
@jplock Can you please release maven artifact for current master branch. I tested it locally, and this is working fine.
