### ISSUE TITLE
com.fasterxml.jackson.databind.JavaType com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType(com.fasterxml.jackson.databind.type.TypeBindings)

### ISSUE THREAD

**Issue by SakuraLxm** [smoketurner/dropwizard-swagger#282]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/22929594/198815036-f2540108-b385-4c5f-ba1a-5ff92469ba5b.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/22929594/198815045-ea877bd2-b3ad-4560-b8ea-7fab6277a5b5.png">
but. my jackson version is 2.13.2 ,so i make mistake. 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/22929594/198815112-04acc1a6-3caa-4bb7-9112-72a9ea62933d.png">

how can i fix it . my all code is dependen on 2.13.2 ..

**Comment by kuldeepiitg** [comment]
+1

**Comment by shlomiken** [comment]
+1

**Comment by sasirekhamsvl** [comment]
+1
