### ISSUE TITLE
Jakarta XML support

### ISSUE THREAD

**Issue by JackPGreen** [smoketurner/dropwizard-swagger#298]
I can see in https://github.com/smoketurner/dropwizard-swagger/pull/200 that moves have been made towards using the `jakarta` XML namepace, but the `swagger-core` version used internally uses `javax.xml.bind` in `io.swagger.jackson.SwaggerAnnotationIntrospector`.

Newer version of swagger offer `jakarta`-centric derivatives - perhaps `dropwizard-swagger` could use these, and upgrade to the latest versions as well?

**Comment by jplock** [comment]
That will need to be coordinated with the Dropwizard v3 and v4 changes - https://github.com/dropwizard/dropwizard/discussions/5694

**Comment by jarl-dk** [comment]
Seems like this is resolved in #309
