### ISSUE TITLE
OpenAPI definition needs context root

### ISSUE THREAD

**Issue by janenicholson** [smoketurner/dropwizard-swagger#299]
https://github.com/smoketurner/dropwizard-swagger/blob/7a6dc7aca0636f80d4e895a1a621f9a80a37623f/src/main/java/io/federecio/dropwizard/swagger/SwaggerBundleConfiguration.java#L345

When configuring the OpenAPI definition you need to put the applicationContext as the url in a Server list entry, or you'll get the swagger ui sending to /resource instead of /applicationContext/resource

The symptom is as described here: https://stackoverflow.com/questions/73212697/how-to-add-context-path-in-the-swagger-ui-open-api-in-try-it-out

like
  .openAPI(oas.info(info).server(List.of(new Server().url(applicationContext))))

**Comment by Jdevas** [comment]
Any Update with this? Facing same issue in 2.1.6-1 version
