### ISSUE TITLE
Dropwizard 3 support

### ISSUE THREAD

**Issue by JackPGreen** [smoketurner/dropwizard-swagger#307]
Dropwizard 3 has been released, but this changes some of the package declarations.

E.G. `io.dropwizard.Configuration` is now `io.dropwizard.core.Configuration`.

https://www.dropwizard.io/en/release-3.0.x/manual/upgrade-notes/upgrade-notes-3_0_x.html#dropwizard-package-structure-and-jpms

Is it possible for `dropwizard-swagger` to be upgraded to use this?

**Comment by jplock** [comment]
I need to get the master branch built and released with 2.1.6, then I’ll rename the branch to 2.1.x, and create a 3.0.x branch for these updates

**Comment by sz-liva** [comment]
Please, update also branch 2.0.12-1 to support Dropwizard 3.

**Comment by sz-liva** [comment]
> Please, update also branch 2.0.12-1 to support Dropwizard 3.

Never mind. I migrated to the version 2.1.4-1 and dropwizard-swagger is the only thing that is holding me back from migration of my project to Dropwizard 3.

**Comment by jarl-dk** [comment]
The #310 should do it.

**Comment by jplock** [comment]
I published v3.0.0-1 yesterday
