### ISSUE TITLE
Annotations in Swagger & Dropwizard v3

### ISSUE THREAD

**Issue by ahalma** [smoketurner/dropwizard-swagger#317]
Thank you for creating a release compatible with Dropwizard v3!

It seems that `io.swagger.annotations.*` is no longer the way to go, but rather `io.swagger.v3.oas.annotations.*`.

Does that mean I have to refactor all `@ApiParam` to `@Parameter` and friends in my Resources, or is there an easier way?

**Comment by sandeepnkulkarni** [comment]
I am also in process of upgrading to Dropwizard v3 with dropwizard-swagger compatible release. From what I can understand so far, there is no way out here. There is upgrade of major version of swagger to openapi. We have to manually change them. Also don't forget to do the same for `@ApiOperation` and `@ApiResponses` as well.

To get an idea refer to diff in sample code: https://github.com/smoketurner/dropwizard-swagger/commit/fc53f0b7721794a522734d6b1e7183586d3abe3e#diff-e58e2be5da65a75b940921871fff03661057eff18d12ea47f0d137e40a7c5ce2

**Comment by sandeepnkulkarni** [comment]
@ahalma, I have completed the changes and I can confirm that swagger annotations needs to be used from `io.swagger.v3.oas.annotations.*` only for everything to work correctly. However, there are many differences how new annotations work. Some of the annotations have undergone drastic changes, so we have to be careful while making the changes.

JFYI, we are facing an issue with 'Try it button' which is I think related to deprecation of basePath support in OpenAPI.

> In OpenAPI 3.0, you use the servers array to specify one or more base URLs for your API. servers replaces the host, basePath and schemes keywords used in OpenAPI 2.0. Each server has an url and an optional Markdown-formatted description.

More information: https://swagger.io/docs/specification/api-host-and-base-path/

We make use of `applicationContextPath` and `rootPath` in our application. After upgrading to new version with Dropwizard v3 compatible release, 'Try it button' is not working anymore. It is generating requests which is not prefixing applicationContextPath and rootPath to the URLs. Hence the requests are failing with 404 error.

In v2 of dropwizard-swagger, `basePath` was correctly getting added to `swagger.json`. But not anymore in v3, nor we can see any entry for `servers`. We are still trying to understand if we have missed anything while upgrading but so far it looks like some issue with dropwizard-swagger.
