### ISSUE TITLE
SwaggerBundle.run() enables JsonInclude.Include.NON_NULL serialization

### ISSUE THREAD

**Issue by jerrylawson** [smoketurner/dropwizard-swagger#33]
It is not clear why this ObjectMapper setting is being enabled in the context of swagger:

https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/swagger/SwaggerBundle.java#L62-L63

I believe this should not be done.

**Comment by jplock** [comment]
Resolved by https://github.com/smoketurner/dropwizard-swagger/pull/35
