### ISSUE TITLE
Dropwizard 3.0/4.0 Support

### ISSUE THREAD

**Issue by mikeholler** [smoketurner/dropwizard-swagger#334]
The main page does not list Dropwizard 3.0 or 4.0 as being supported, and I've found some issues with this support in practice. Can we get official support for the new Dropwizard versions?

**Comment by jplock** [comment]
I've created releases for both of those but I personally no longer use this library. I'd be happy to make someone else a contributor to this repo and continue to push up releases to Maven Central, but it is difficult for me to test and maintain this library going forward without others stepping up.

**Comment by timmolter** [comment]
This seems to work fine for DW 4.0.x

**Comment by sheetalj2205** [comment]
> This seems to work fine for DW 4.0.x

Hey, its not working for me with DW 4.x. Can you please let me know how it worked for you. I am getting either 500 or 404
