### ISSUE TITLE
Java 17 Support

### ISSUE THREAD

**Issue by chris-cynation** [smoketurner/dropwizard-swagger#338]
Hi,

I've been trying to trying to get a microservice to use Java 17 but swagger has issues when initialising. 

I've discovered that swagger core has -jakarta artifacts (ie swagger-core-jakarta) to support java 17.

Switching to that gives me the following error.

```
java.lang.NoSuchMethodError: 'java.lang.String io.swagger.v3.oas.integration.api.OpenAPIConfiguration.getDefaultResponseCode()'

at io.swagger.v3.jaxrs2.Reader.setConfiguration(Reader.java:221)
	at io.swagger.v3.jaxrs2.Reader.<init>(Reader.java:123)
	at io.swagger.v3.jaxrs2.Reader.<init>(Reader.java:115)
	at io.swagger.v3.jaxrs2.Reader.<init>(Reader.java:103)
	at io.swagger.v3.jaxrs2.integration.JaxrsOpenApiContext.buildReader(JaxrsOpenApiContext.java:33)
	at io.swagger.v3.oas.integration.GenericOpenApiContext.init(GenericOpenApiContext.java:448)
	at io.swagger.v3.oas.integration.GenericOpenApiContext.init(GenericOpenApiContext.java:47)
	at io.swagger.v3.jaxrs2.integration.JaxrsOpenApiContextBuilder.buildContext(JaxrsOpenApiContextBuilder.java:44)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:82)
	at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:47)
```
	
`SwaggerBundle.java:82 = new JaxrsOpenApiContextBuilder().openApiConfiguration(oasConfiguration).buildContext(true);`

**Comment by rcirmira** [comment]
@chris-cynation I think you need to provide versions of dropwizard and dropwizard-swagger you're using, otherwise it's hard to advice anything. Ideal would be result of `mvn dependency:tree`

Your error suggests you're using swagger-core with OpenAPI v3 and it's not included in the list of dependencies.

**Comment by chris-cynation** [comment]
I'm using Dropwizard 4.0.4 with version 4.0.0-1 of dropwizard-swagger.

The error is showing that dropwizard-swagger doesn't support the jakarta version of swagger.

If i switch to using the normal swagger-core with Java 17 i get the following error message.

`! java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String[] java.nio.charset.Charset.aliases accessible: module java.base does not "opens java.nio.charset" to unnamed module @44c8afef
! at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
! at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
! at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
! at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
! at org.glassfish.jersey.linking.FieldDescriptor$1.run(FieldDescriptor.java:63)
! at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
! at org.glassfish.jersey.linking.FieldDescriptor.setAccessibleField(FieldDescriptor.java:60)
! at org.glassfish.jersey.linking.FieldDescriptor.getFieldValue(FieldDescriptor.java:41)
! at org.glassfish.jersey.linking.FieldProcessor.processLinks(FieldProcessor.java:154)
! at org.glassfish.jersey.linking.FieldProcessor.processMember(FieldProcessor.java:174)
! at org.glassfish.jersey.linking.FieldProcessor.processLinks(FieldProcessor.java:154)
! at org.glassfish.jersey.linking.FieldProcessor.processLinks(FieldProcessor.java:65)
! at org.glassfish.jersey.linking.ResponseLinkFilter.filter(ResponseLinkFilter.java:58)
! at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:172)
! at org.glassfish.jersey.server.ContainerFilteringStage$ResponseFilterStage.apply(ContainerFilteringStage.java:139)
! at org.glassfish.jersey.process.internal.Stages.process(Stages.java:147)
! at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:378)
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:370)
! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:358)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
! at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:36)
! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:46)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:40)
! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:314)
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:267)
! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
! at io.dropwizard.metrics.jetty11.InstrumentedHandler.handle(InstrumentedHandler.java:310)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:822)
! at io.dropwizard.jetty.ZipExceptionHandlingGzipHandler.handle(ZipExceptionHandlingGzipHandler.java:26)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:46)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
! at org.eclipse.jetty.server.Server.handle(Server.java:563)
! at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
! at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
! at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
! at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
! at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
! at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
! at java.base/java.lang.Thread.run(Thread.java:833)
`
I tried using both versions of the artifacts (jakarta and normal) and you can't run with both.

**Comment by rcirmira** [comment]
swagger-core doesn't support JDK 17, it looks there's https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-project-jakarta  where swagger-core team is trying to upgrade swagger to use jakarta version of Java. In my opinion only this version will be able to support JDK 17, but based on github contents it isn't implemented yet...

You're using dropwizard-swagger https://github.com/smoketurner/dropwizard-swagger/tree/4.0.x and it's using dependencies based on parent https://github.com/smoketurner/dropwizard-swagger/blob/4.0.x/pom.xml#L21, and unfortunately that parent is still pointing to `2.2.9` swagger-* artifacts

and method `getDefaultResponseCode` was implemeneted in 2.2.17+
https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-integration/src/main/java/io/swagger/v3/oas/integration/api/OpenAPIConfiguration.java#L70

It most likely means dropwizard-swagger in version 4.0.0-1 is using too old version of OpenAPI...
