### ISSUE TITLE
Swagger-core's info.contact.{email,url} cannot be set from SwaggerBundleConfiguration

### ISSUE THREAD

**Issue by jerrylawson** [smoketurner/dropwizard-swagger#34]
It would be good to be able to define the Contact.email and Contact.url via SwaggerBundleConfiguration.

Suggested implementation is to add Json properties to SwaggerBundleConfiguration for

`String contactEmail;
 String contactUrl`

and copy these values into the Config.info.contact.{email,url} objects when configuring Config in SwaggerBundleConfiguration.build().

**Comment by jplock** [comment]
Resolved by https://github.com/smoketurner/dropwizard-swagger/pull/36
