### ISSUE TITLE
resourcePackage must not be empty

### ISSUE THREAD

**Issue by Zaeem6100** [smoketurner/dropwizard-swagger#351]
I have added the correct config i am getting this error again and again 

![image](https://github.com/smoketurner/dropwizard-swagger/assets/32678310/7edfd01b-120d-409a-a357-df6288fe9ee4)

**Comment by jplock** [comment]
I don't have the bandwidth to troubleshoot this right now. If someone else would like to submit a PR, I'd be happy to review it.
