### ISSUE TITLE
Add components/security to SwaggerBundleConfiguration in 4.x

### ISSUE THREAD

**Issue by DanyBv** [smoketurner/dropwizard-swagger#358]
Is it possible to cherry-pick [this commit](https://github.com/smoketurner/dropwizard-swagger/commit/d456d537e57a38bbc86e603b9490641d5744def5) into the 4.0.0 branch to include the components and security changes in the SwaggerBundleConfiguration?

**Comment by dharmil** [comment]
+1 this would be very useful

**Comment by setopet** [comment]
+1
