### ISSUE TITLE
Make "resourcePackage" optional/implied

### ISSUE THREAD

**Issue by dsmiley** [smoketurner/dropwizard-swagger#41]
Instead of making "resourcePackage" required, I think this module could auto-detect it based on what is resources exist since DropWizard knows about them; no?

**Comment by jplock** [comment]
I think that's a good suggestion.  Would you want to submit a pull request implementing that functionality?

**Comment by dsmiley** [comment]
Maybe someday.  As it is I spend a good deal of free time on open-source.
