### ISSUE TITLE
@Auth params showing in swagger.json

### ISSUE THREAD

**Issue by apetersson** [smoketurner/dropwizard-swagger#44]
i switched from 0.7.0 (federecio/dropwizard-swagger) to 0.9. i noticed that suddenly @Auth params were included in the swagger.json. is there a workaround for this?

**Comment by jplock** [comment]
Nothing was changed recently to exclude or include @Auth params.  If you find a solution though to making this configurable, I'll happily review a pull request.

**Comment by apetersson** [comment]
i made a manual workaround by using "@Auth @ApiParam(hidden = true) User user" for my auth params. there could be a generic solution, though

**Comment by hmanriquez-pts** [comment]
You can also use the Dropwizard authentication annotation @PermitAll on your resource, if you have it set up.

Look at the Dropwizard Authentication documentation under Protecting Resources for a better explanation.

**Comment by Keitarokido** [comment]
You can also use the Dropwizard authentication annotation @PermitAll on your resource, if you have it set up.

Look at the Dropwizard Authentication documentation under Protecting Resources for a better explanation.

**Comment by omnipitous** [comment]
Just pinging this thread since this issue is still real: While upgrading to the latest DropWizard we tried to move from dropwizard-swagger 1.1.0-1 -> 1.3.0-1 and encountered this issue. Not only does the UI not pass our authentication to the endpoints but, since it's not respecting the @auth tag, it also won't let you run any GET endpoints because it keeps trying to pass them the @auth Object as a "body"..  Reverting to 1.1.0-1 fixes the issue (**still using the latest DropWizard deps) so something definitely changed in this code base. A diff between those tags should yield something??

**Comment by mikeholler** [comment]
I'm also having this issue. Any other ideas on it?

**Comment by duckmatt** [comment]
Note that the [swagger docs](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#requestbody) state:

> Also without a @RequestBody annotated parameter and with no @RequestBody annotation at method level or as field of Operation#requestBody, if a parameter is annotated with @Parameter with no in field specified and no JAX-RS annotation (@QueryParam, @HeaderParam, @BeanParam), the parameter is resolved as a request body.This happens only when the http method is associated with the @PUT or @POST verb. **In case of multiple such parameters, only the first is considered.**

So ideally if the `@Auth` param is after the the actual request body param it should not be considered. For some reason it is considered, it should probably be fixed upstream in swagger core but as a workaround this can be done by overriding the AuthParamFilter's `isParamAllowed` to exclude params after the first body

```java                    
if (parameter instanceof BodyParameter) {
    return operation.getParameters().stream().filter(x -> x instanceof BodyParameter)
        .findFirst()
        .filter(x -> x == parameter)
        .isPresent();
}
```

**Comment by jadams74** [comment]
This is still an issue. @duckmatt  I don't follow where you suggest making the change.

**Comment by duckmatt** [comment]
@jadams74 it's less than ideal but something like:

```java
@Override
public void initialize(Bootstrap<YourConfiguration> bootstrap) {
    bootstrap.addBundle(new SwaggerBundle<YourConfiguration>() {
        @Override
        protected SwaggerBundleConfiguration getSwaggerBundleConfiguration(YourConfiguration configuration) {
            return configuration.swaggerBundleConfiguration;
        }

        @Override
        protected void run(xyz) {
            super.run(xyz);
            
            FilterFactory.filter(new AuthFilter() {
                @Override
                public boolean isParamAllowed(xyz) {
                    if (parameter instanceof BodyParameter) {
                        return operation.getParameters().stream().filter(x -> x instanceof BodyParameter)
                            .findFirst()
                            .filter(x -> x == parameter)
                            .isPresent() && (api.getMethod().equalsIgnoreCase("POST") || api.getMethod().equalsIgnoreCase("PUT"));
                    }
                    return super.isParamAllowed(xyz);
                }
            });
        }
    });
}
```

It's a rough gist of it using the example bootstrapping from the readme
