### ISSUE TITLE
Dropwizard warning - com.google.inject.servlet.InternalServletModule: You are attempting to use a deprecated API

### ISSUE THREAD

**Issue by darrenhaken** [smoketurner/dropwizard-swagger#48]
When I use the plugin I get the following warnings when launching Dropwizard 1.0.0:

**WARN  [2016-08-09 19:51:04,751] com.google.inject.servlet.InternalServletModule: You are attempting to use a deprecated API (specifically, attempting to @Inject ServletContext inside an eagerly created singleton. While we allow this for backwards compatibility, be warned that this MAY have unexpected behavior if you have more than one injector (with ServletModule) running in the same JVM. Please consult the Guice documentation at https://github.com/google/guice/wiki/Servlets for more information.**

Any idea what could be causing this? 

I narrowed it down to it happens when the Swagger bundle is added to Dropwizard.

**Comment by jplock** [comment]
There isn't a lot of code in here, so unless its something with in Swagger itself, I'm not sure what I can do about it.

**Comment by darrenhaken** [comment]
The code I use in my bundle config is:

```
 bootstrap.addBundle(new SwaggerBundle<AppConfiguration>() {
            @Override
            protected SwaggerBundleConfiguration getSwaggerBundleConfiguration(AppConfiguration configuration) {
                return configuration.swaggerBundleConfiguration;
            }
        });
```

If I comment this out the warnings go away
