### ISSUE TITLE
swagger UI bad control placement

### ISSUE THREAD

**Issue by aparslew** [smoketurner/dropwizard-swagger#52]
Hi,

(I'm new to dropwizard and swagger so please excuse me if this is something obvious I've missed.)

I tried integrating dropwizard-swagger into my project.  Everything works fine except that the UI is mis-placing the controls at the top (see below); I tried viewing from both Chrome and Firefox.  All references from the page (css, etc) seem fine so I'm not sure what could be causing this - presumably it's related to the version of swagger-ui being used?  Any help in resolving this would be appreciated.

![swagger_screenshot](https://cloud.githubusercontent.com/assets/22097638/18386531/9e736108-768f-11e6-9698-3d874f122125.PNG)

Regards,
Adam.

**Comment by jplock** [comment]
I've seen this too. The swagger UI includes built in auth controls that we should be using. I've been trying to figure out how to get the proper security definitions to render in the JSON to show the UI controls.

**Comment by jplock** [comment]
Then we can remove the drop down customizations.

**Comment by aparslew** [comment]
Ah cool; thanks Justin.

**Comment by jplock** [comment]
Fixed in v1.0.5-1
