### ISSUE TITLE
Build error with dropwizard 1.0.3

### ISSUE THREAD

**Issue by abhishek199-dhn** [smoketurner/dropwizard-swagger#58]
Hey,
I'm using dropwizard-swagger 1.0.0-1 with dropwizard 1.0.3 and not able to build it.

Build Error:-

[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce)  ---
[WARNING] 
Dependency convergence error for xml-apis:xml-apis:1.0.b2 paths to dependency are:
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-io.dropwizard:dropwizard-hibernate:1.0.3
    +-org.hibernate:hibernate-core:5.1.0.Final
      +-dom4j:dom4j:1.6.1
        +-xml-apis:xml-apis:1.0.b2
and
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-com.smoketurner:dropwizard-swagger:1.0.0-1
    +-xml-apis:xml-apis:1.4.01

[WARNING] 
Dependency convergence error for org.reflections:reflections:0.9.10 paths to dependency are:
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-com.smoketurner:dropwizard-swagger:1.0.0-1
    +-io.swagger:swagger-jersey2-jaxrs:1.5.9
      +-io.swagger:swagger-jaxrs:1.5.9
        +-org.reflections:reflections:0.9.10
and
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-com.fiestacabin.dropwizard.quartz:dropwizard-quartz:0.7.2
    +-org.reflections:reflections:0.9.9

[WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for xml-apis:xml-apis:1.0.b2 paths to dependency are:
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-io.dropwizard:dropwizard-hibernate:1.0.3
    +-org.hibernate:hibernate-core:5.1.0.Final
      +-dom4j:dom4j:1.6.1
        +-xml-apis:xml-apis:1.0.b2
and
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-com.smoketurner:dropwizard-swagger:1.0.0-1
    +-xml-apis:xml-apis:1.4.01
, 
Dependency convergence error for org.reflections:reflections:0.9.10 paths to dependency are:
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-com.smoketurner:dropwizard-swagger:1.0.0-1
    +-io.swagger:swagger-jersey2-jaxrs:1.5.9
      +-io.swagger:swagger-jaxrs:1.5.9
        +-org.reflections:reflections:0.9.10
and
+-com.indroydlabs:rfidServer:1.0-SNAPSHOT
  +-com.fiestacabin.dropwizard.quartz:dropwizard-quartz:0.7.2
    +-org.reflections:reflections:0.9.9
]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

Can you help me out with this.?

**Comment by jplock** [comment]
I'm working on fixing this but we need swagger-core 1.5.11 released before I can publish this updated version.

**Comment by abhishek199-dhn** [comment]
When is the release date for swagger-core 1.5.11 .?
I need to deploy my service to prod. so i can plan according to it.

**Comment by jplock** [comment]
I don't know. The swagger team was shooting for last week but the release never happened.

**Comment by abhishek199-dhn** [comment]
okay. Thanks man!

**Comment by jplock** [comment]
swagger-core 1.5.11 was finally released and I just published a dropwizard-swagger 1.0.5-1 version
