### ISSUE TITLE
Turn swagger off for certain folders

### ISSUE THREAD

**Issue by shail** [smoketurner/dropwizard-swagger#59]
When I run my server I get a bunch of debug warnings that look like this:

```
DEBUG [2016-12-16 02:17:28,461] org.reflections.Reflections: could not scan file META-INF/maven/io.dropwizard/dropwizard-jersey/pom.properties in url jar:file:/Users/shail/repos/testproj/dist/testingProj.jar!/ with scanner SubTypesScanner
```

Is there a way of turning swagger off for certain folders? Not sure if you've seen anything like this before

**Comment by jplock** [comment]
Haven't seen anything like this before
