### ISSUE TITLE
Value.Immutable beans

### ISSUE THREAD

**Issue by gokumar** [smoketurner/dropwizard-swagger#65]
I am using Value.Immutable classes as part of my rest input/output. Swagger does not seem to understand these beans as there are no getters and setters in the immutable class definition. Because of this, I don't see anything in the Example section in swagger.

How do I enable Value.Immutable classes?

I am using 1.0.0-1

**Comment by jplock** [comment]
Please file an issue on https://github.com/swagger-api/swagger-core to see about supporting this.
