### ISSUE TITLE
Swagger page not showing Auth Header/ Api Key Options

### ISSUE THREAD

**Issue by moezubair** [smoketurner/dropwizard-swagger#66]
Hey,
Dropwizard-swagger versions after 1.0.0-1 are removing/hiding the auth/header api key dropdown and input box from the header. 
How do I get them to appear again?

This is what I am getting from 1.0.5-4:
![1-26-2017 11-11-22 am](https://cloud.githubusercontent.com/assets/3712264/22339939/b4b22a98-e3b9-11e6-8fe0-1c949b1dc9bb.jpg)

This is what I want, and get from 1.0.0-1:
![image](https://cloud.githubusercontent.com/assets/3712264/22339985/e004e42e-e3b9-11e6-9cae-663bef5053a1.png)

**Comment by jplock** [comment]
I removed it to make updating the UI easier, simplify the tests, and support the native swagger `@SecurityDefinition` annotations.  https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/sample/SampleResource.java#L19

**Comment by kslats9** [comment]
Is there a simple way to add it back? Could you give an example of adding an Authorization header annotation to a Dropwizard resource?

**Comment by jplock** [comment]
@kslats9 https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/sample/SampleApplication.java#L40 has an example of adding basic auth.  Also http://www.dropwizard.io/1.0.5/docs/manual/auth.html#basic-authentication
