### ISSUE TITLE
resourcePackage doesn't like spaces after commas 

### ISSUE THREAD

**Issue by bladecatcher** [smoketurner/dropwizard-swagger#69]
The following works fine:
```
swagger:
  resourcePackage: com.abc,com.def
```

The below doesn't include `com.def` because of the space before it
```
swagger:
  resourcePackage: com.abc, com.def
```

**Comment by jplock** [comment]
That value isn't sanitized before being sent into swagger-core - https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/swagger/SwaggerBundleConfiguration.java#L283

Maybe file an issue https://github.com/swagger-api/swagger-core/issues instead.
