### ISSUE TITLE
Support HTTP PATCH

### ISSUE THREAD

**Issue by m8r-ubnc5g** [smoketurner/dropwizard-swagger#7]
All I know is, that Swagger supports 'PATCH' but this does not work with actual version of this bundle. Googled and found the 'supportedSubmitMethods' setting, but 'SwaggerBundleConfiguration' does not publish this setting. Please add more configuration options to support this.

If there is workaround, let me know.

**Comment by jplock** [comment]
Pull requests are welcome

**Comment by m8r-ubnc5g** [comment]
I checked '/swagger-static/swagger-ui.js'. There patch should be supported, but this does not work for me:

var supportedOperationMethods = ['delete', 'get', 'head', 'options', 'patch', 'post', 'put'];


I'll check this out the next days, if this is just my fault or a general problem.

**Comment by m8r-ubnc5g** [comment]
Jeah thats the Problem. Using @io.swagger.jaxrs.PATCH solves the problem. Sorry for the spam here ;-)
