### ISSUE TITLE
Swagger https call

### ISSUE THREAD

**Issue by GillesBodart** [smoketurner/dropwizard-swagger#70]
Hello, First of all thank you for this project,

I've some troubles when I try my API, the call are made on http but the server only allowed https,

#### here's my config ####

    swagger:
      resourcePackage: <package>
      scheme: https

is it normal ? 

Thanks in advance

**Comment by jplock** [comment]
Try changing `scheme` to `schemes` as in https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/java/io/federecio/dropwizard/swagger/SwaggerBundleConfiguration.java#L240

**Comment by GillesBodart** [comment]
I tryed but : 

Failed to parse configuration at: swagger.schemes; Can not deserialize instance of java.lang.String[] out of VALUE_STRING token
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.unamur.be.configuration.LilConfiguration["swagger"]->io.federecio.dropwizard.swagger.SwaggerBundleConfiguration["schemes"])

**Comment by GillesBodart** [comment]
Perfect Thanks a lot !
