### ISSUE TITLE
Precompiled with older version of handlebars than current runtime

### ISSUE THREAD

**Issue by jadams74** [smoketurner/dropwizard-swagger#73]
I just started getting the errors below. I didn't update the version of dropwizard or dropwizard-swagger. Any ideas how I fix this:

rdescription: undefinedfileName: undefinedlineNumber: undefinedmessage: "Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1)."name: "Error"number: undefinedstack: "Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).↵    at Object.s [as checkRevision] (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:9353)↵    at Object.i [as template] (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:10785)↵    at s.t.template (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:1306)↵    at https://ipa-find-api.devhelix.com/swagger-static/swagger-ui.js:9:68↵    at https://ipa-find-api.devhelix.com/swagger-static/swagger-ui.js:32281:7"__proto__: Error
    at Object.<anonymous> (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:4780)
    at e (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at Object.e (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:2019)
    at e (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at Object.e.default.e (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:1385)
    at e (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at Object.e.default.t.__esModule.default (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:742)
    at e (https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:330)
    at https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:417
    at https://ipa-find-api.devhelix.com/swagger-static/lib/handlebars-4.0.5.js:1:422
s @ handlebars-4.0.5.js:1
i @ handlebars-4.0.5.js:1
t.template @ handlebars-4.0.5.js:1
(anonymous) @ index.js:8
(anonymous) @ index.js:24

**Comment by jplock** [comment]
That seems like an issue with the bundled JS code, but I'm not sure what would cause that.

**Comment by sbarne3** [comment]
I'm having the same issue

**Comment by jadams74** [comment]
I've only seen this a couple of times. When I package it usually works. No clue what causes it to fail.

**Comment by jadams74** [comment]
I haven't seen this in a while. Closing. No clue how to reliably reproduce.

**Comment by ikrambabai** [comment]
I faced this issue while switching and testing between different versions - Looks like the Javascript content from older jars were sitting in browser cache when the new was being tried. Clearing cache fixed this issue for me.

**Comment by hemapunniakotti** [comment]
Thank you @ikrambabai .. Clearing cache helped :)
