### ISSUE TITLE
Get this to work with 1.1.0

### ISSUE THREAD

**Issue by msmerc** [smoketurner/dropwizard-swagger#74]
Hey,

I see you've made some attempt to get this to work with dropwizard 1.1.0. Any plans to get a release out? :)

**Comment by cristimusat** [comment]
Hi, 

The problem is from jersey-container-servlet-core dependency. 
I managed to fix the tests with a modification in pom.xml

```code
        <dependency>
            <groupId>com.smoketurner</groupId>
            <artifactId>dropwizard-swagger</artifactId>
            <version>1.1.0-1</version>
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish.jersey.containers</groupId>
                    <artifactId>jersey-container-servlet-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.containers</groupId>
            <artifactId>jersey-container-servlet-core</artifactId>
            <version>${jersey.version}</version>
        </dependency>

**Comment by jplock** [comment]
I released a version for 1.1.0 last weekend.

**Comment by cristimusat** [comment]
i am using the version 1.1.0-1 which i think is the version you refer to. 
My problem was that tests for dropwizard were failing due to NoClassDefFound for BackgroundSchedulerLiteral and I fixed it using the above configuration

**Comment by cristimusat** [comment]
i doubled checked and if i remove the exception the application doesn't start. 
I have the following error:
org/glassfish/jersey/server/internal/RuntimeExecutorsBinder$BackgroundSchedulerLiteral

**Comment by lutzhorn** [comment]
Yes, this is caused by `com.smoketurner:dropwizard-swagger:jar:1.1.0-1` having a dependency on an old `org.glassfish.jersey.containers:jersey-container-servlet-core`. A `mvn dependency:tree` gives:

```
[INFO] +- com.smoketurner:dropwizard-swagger:jar:1.1.0-1:compile
[INFO] |  +- io.dropwizard:dropwizard-assets:jar:1.1.0:compile
[INFO] |  +- io.dropwizard:dropwizard-views:jar:1.1.0:compile
[INFO] |  +- io.dropwizard:dropwizard-views-freemarker:jar:1.1.0:compile
[INFO] |  |  \- org.freemarker:freemarker:jar:2.3.23:compile
[INFO] |  \- io.swagger:swagger-jersey2-jaxrs:jar:1.5.13:compile
[INFO] |     +- io.swagger:swagger-jaxrs:jar:1.5.13:compile
[INFO] |     |  +- io.swagger:swagger-core:jar:1.5.13:compile
[INFO] |     |  |  \- io.swagger:swagger-models:jar:1.5.13:compile
[INFO] |     |  |     \- io.swagger:swagger-annotations:jar:1.5.13:compile
[INFO] |     |  \- org.reflections:reflections:jar:0.9.10:compile
[INFO] |     |     \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |     \- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.1:compile

```

I am not sure who has to fix this dependency.

**Comment by lutzhorn** [comment]
Reason: https://github.com/swagger-api/swagger-core/blob/18d7141f2f94a409d533284a6a7bf431e3904a32/pom.xml#L493

**Comment by lutzhorn** [comment]
Reason behind the reason: https://github.com/ronmamo/reflections/issues/172

**Comment by phantomastray** [comment]
Has anyone got any workaround to make it work on dropwizard `1.1.0` ?
All I get on starting server is:
<img width="332" alt="screen shot 2018-04-10 at 4 35 05 pm" src="https://user-images.githubusercontent.com/8266588/38553537-39589fac-3cdd-11e8-8cad-4973a13b6465.png">
