### ISSUE TITLE
Sort operations

### ISSUE THREAD

**Issue by danielborges93** [smoketurner/dropwizard-swagger#78]
There is a way to change the order all api operations? I intend to sort alphanumerically.

Thanks!

**Comment by jplock** [comment]
It's currently hardcoded to sort alphanumerically - https://github.com/smoketurner/dropwizard-swagger/blob/master/src/main/resources/io/federecio/dropwizard/swagger/index.ftl#L80

**Comment by Crayan** [comment]
Hi,

The operations are not guaranteed to be sorted alphabetically, and the order is somewhat random.
As you mentioned, in the code, I see there's a parameter "apisSorter" with value "alpha" hard coded. However, is it up to date? I notice Swagger provide another two parameters, operationsSorter and tagsSorter, but there's no apisSorter. (cf. [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md))

FYI, I use version 1.1.2-1. In my scenario, I have a tag
**/api/latest/installers**
that groups two operations:
**/api/latest/installers/scripts**
**/api/latest/installers/binaries**

If operations are sorted alphabetically, *scripts* operation should appear after *binaries* operation, but in fact sometimes it appears before it. If I place the **scripts** method before **binaries** within the java Resource class, then the operations order is **scripts** before **binaries** as well. The sort seems not really working.

Also, is it possible that we can have a method to customize the Swagger UI ftl template and pass it to the library?

Thank you!

**Comment by reftel** [comment]
It seems this has changed in swagger-ui v3. The config option is now called `tagsSorter`, but dropwizard-swagger still sets the old, now ignored, `apisSorter`.
