### ISSUE TITLE
Swagger 1.1.1-1 in conjunction with shadow plugin

### ISSUE THREAD

**Issue by bkuraku** [smoketurner/dropwizard-swagger#84]
I am using the shadow plugin to build fat Jars https://github.com/johnrengelman/shadow 
Running the fat Jar with the version 1.1.1-1 gives these warnings. But it works and runs without warnings  if I use the version 1.1.0-1.
`
WARN  [2017-06-27 07:44:54,016] org.reflections.Reflections: could not get type for name org.jaxen.NamespaceContext from any class loader
! java.lang.ClassNotFoundException: org.jaxen.NamespaceContext
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
! Causing: org.reflections.ReflectionsException: could not get type for name org.jaxen.NamespaceContext
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
! at org.reflections.Reflections.<init>(Reflections.java:126)
! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276)
! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:287)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:66)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:33)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at com.zulily.taskmaster.TaskMasterApplication.main(TaskMasterApplication.java:17)
WARN  [2017-06-27 07:44:54,017] org.reflections.Reflections: could not get type for name javax.mail.Authenticator from any class loader
! java.lang.ClassNotFoundException: javax.mail.Authenticator
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
! Causing: org.reflections.ReflectionsException: could not get type for name javax.mail.Authenticator
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
! at org.reflections.Reflections.<init>(Reflections.java:126)
! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276)
! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:287)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:66)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:33)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at com.zulily.taskmaster.TaskMasterApplication.main(TaskMasterApplication.java:17)
WARN  [2017-06-27 07:44:54,017] org.reflections.Reflections: could not get type for name org.jaxen.dom4j.Dom4jXPath from any class loader
! java.lang.ClassNotFoundException: org.jaxen.dom4j.Dom4jXPath
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:388)
! ... 14 common frames omitted
! Causing: org.reflections.ReflectionsException: could not get type for name org.jaxen.dom4j.Dom4jXPath
! at org.reflections.ReflectionUtils.forName(ReflectionUtils.java:390)
! at org.reflections.Reflections.expandSuperTypes(Reflections.java:381)
! at org.reflections.Reflections.<init>(Reflections.java:126)
! at io.swagger.jaxrs.config.BeanConfig.classes(BeanConfig.java:276)
! at io.swagger.jaxrs.config.BeanConfig.scanAndRead(BeanConfig.java:240)
! at io.swagger.jaxrs.config.BeanConfig.setScan(BeanConfig.java:221)
! at io.federecio.dropwizard.swagger.SwaggerBundleConfiguration.build(SwaggerBundleConfiguration.java:287)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:66)
! at io.federecio.dropwizard.swagger.SwaggerBundle.run(SwaggerBundle.java:33)
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:200)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:42)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:74)
! at io.dropwizard.Application.run(Application.java:89)
! at com.zulily.taskmaster.TaskMasterApplication.main(TaskMasterApplication.java:17)
`

**Comment by maggie-lagos** [comment]
Hey @bkuraku! I confirm I'm getting the same issue with 1.1.1-1 and maven-shade-plugin 2.4.1 configured as recommended [in the docs](http://www.dropwizard.io/1.1.2/docs/getting-started.html#building-fat-jars). Switching to 1.1.0-1 seems to work for me as well.

**Comment by EXPEvmaskoliunas** [comment]
It might be due to https://github.com/ronmamo/reflections/issues/171 and https://github.com/ronmamo/reflections/issues/190

I excluded reflections:0.9.11 in my project and switched to 0.9.10. The errors have gone.
