### ISSUE TITLE
SwaggerUI operations do not work if server is being run behind https

### ISSUE THREAD

**Issue by bdbull** [smoketurner/dropwizard-swagger#87]
My app is being run behind https, but all of the requests from swaggerui are being sent to http.  Swaggerui is able to get the swagger.json and display all of the available methods, but when I attempt to "Try it out" they are all sent to http instead.  This renders swaggerui useless as none of the operations work at all.  See screenshot (identifiable data removed)
![swagger-http-https](https://user-images.githubusercontent.com/1843618/30229956-07ad27a8-94b2-11e7-902d-02f4951af720.png)

**Comment by senki1988** [comment]
For me https is working. In my drowpizard config the https scheme is set in "swagger":
`schemes: ["http","https"]`

**Comment by bdbull** [comment]
Yes!  That works!!!
