### ISSUE TITLE
Dropwizard 1.2 support?

### ISSUE THREAD

**Issue by aharnly-amplify** [smoketurner/dropwizard-swagger#89]
Hi, appreciate the work on this. Is support for Dropwizard 1.2 in the cards?

**Comment by jplock** [comment]
Yea. I’ll try and and get this published soon.

**Comment by jplock** [comment]
I remembered why I haven't done this already:  something related to contact information is now failing in the tests and I don't know why.

**Comment by jplock** [comment]
Just published v1.2.2-1 to Maven Central
