### ISSUE TITLE
Swagger.json Internal 500 server error (NullPointerException)

### ISSUE THREAD

**Issue by MasonFI** [smoketurner/dropwizard-swagger#98]
So I followed the basic tutorial on Readme. My localhost:8080/swagger loads, but swagger.json produces 500 Internal Server error.

Log says:
`io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 83d84f7afce1323b
! java.lang.NullPointerException: null
! at io.swagger.core.filter.SpecFilter.filter(SpecFilter.java:47)`

I have a config.yml that says:
swagger:
  resourcePackage: com.company.app.api.resource

If I remove that config, app wont start so config is read.

com.company.app.api.resource contains class WorkResource.java that has @ApiOperation and @ApiResponses annotations. Endpoints defined in that class return DTO classes from another package, is that package required also in resourcePackage config? I have added that package to config also, but problem stays.

What am I doing wrong?

**Comment by MasonFI** [comment]
Solved it. I did not know that you need define @Api annotation in top of resource class.

**Comment by Ayan07** [comment]
@MasonFI I have use @Api annotation on top of my resource class but it's still showing the same error for me

**Comment by sheetalj2205** [comment]
> [@MasonFI](https://github.com/MasonFI) I have used @Api annotation on top of my resource class but it's still showing the same error for me.

Hey, same for me
I've used @Tag still it is showing

![Image](https://github.com/user-attachments/assets/bae2da01-5df8-43fc-a696-b063e9bb936a)

Can you please tell me how did you solve it?

**Comment by MasonFI** [comment]
> > [@MasonFI](https://github.com/MasonFI) I have used @Api annotation on top of my resource class but it's still showing the same error for me.
> 
> Hey, same for me I've used [@tag](https://github.com/tag) still it is showing
> 
> ![Image](https://github.com/user-attachments/assets/bae2da01-5df8-43fc-a696-b063e9bb936a)
> 
> Can you please tell me how did you solve it?

Hi, sorry but its so long a time so I don't remember. But I have a feeling that it worked the way it was told in basic tutorial.

But also versions have changed a lot since, I guess.
