### ISSUE TITLE
@JsonIgnoreProperties annotation is ignored

### ISSUE THREAD

**Issue by MasonFI** [smoketurner/dropwizard-swagger#99]
I have bidirectional linking (ManyToMany) between two classes and to prevent infinite loop I have set @JsonIgnoreProperties({ "property" }) to both classes.

Currently generated Swagger docs ignore @JsonIgnoreProperties annotation and generated endpoint output is wrong.

**Comment by jplock** [comment]
Probably needs to be reported on https://github.com/swagger-api/swagger-core
